version: '3.9'

services:
  db:
    container_name: wallet-db
    image: mysql:8.0.31
    restart: always
    environment:
      MYSQL_DATABASE: wallet-db
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'