import { Zodios } from '@zodios/core';
import { ZodiosHooks } from '@zodios/react';
import Head from 'next/head';

import { FrontendFrameworksDef } from '@/src/common/api';
import { EnvVars } from '@/src/modules/shared/envVars';
import styles from '@/styles/Home.module.css';

const baseUrl = EnvVars.walletApiURL;
const zodios = new Zodios(baseUrl, [...FrontendFrameworksDef]);
const zodiosHooks = new ZodiosHooks('wallet_api', zodios, {
	shouldAbortOnUnmount: true,
});

export default function Home() {
	const { data } = zodiosHooks.useGetFrameworks();
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>

				<ol>
					{data?.data.map((v) => (
						<li key={v}>{v}</li>
					))}
				</ol>
			</main>
		</div>
	);
}
